/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { StructsContactMessagePayloadVcard } from './structsContactMessagePayloadVcard';

export class StructsContactMessagePayload {
    'to': string;
    'vcard': StructsContactMessagePayloadVcard;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "to",
            "baseName": "to",
            "type": "string"
        },
        {
            "name": "vcard",
            "baseName": "vcard",
            "type": "StructsContactMessagePayloadVcard"
        }    ];

    static getAttributeTypeMap() {
        return StructsContactMessagePayload.attributeTypeMap;
    }
}

