/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FileUpload {
    'directPath': string;
    'fileEncSha256': Array<number>;
    'fileLength': number;
    'fileSha256': Array<number>;
    'mediaKey': Array<number>;
    'mimeType': string;
    'url': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "directPath",
            "baseName": "direct_path",
            "type": "string"
        },
        {
            "name": "fileEncSha256",
            "baseName": "file_enc_sha256",
            "type": "Array<number>"
        },
        {
            "name": "fileLength",
            "baseName": "file_length",
            "type": "number"
        },
        {
            "name": "fileSha256",
            "baseName": "file_sha256",
            "type": "Array<number>"
        },
        {
            "name": "mediaKey",
            "baseName": "media_key",
            "type": "Array<number>"
        },
        {
            "name": "mimeType",
            "baseName": "mime_type",
            "type": "string"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return FileUpload.attributeTypeMap;
    }
}

