/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GroupInviteMessagePayload {
    'caption'?: string;
    'expiryMinutes'?: number;
    'inviteCode'?: string;
    'to'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "caption",
            "baseName": "caption",
            "type": "string"
        },
        {
            "name": "expiryMinutes",
            "baseName": "expiry_minutes",
            "type": "number"
        },
        {
            "name": "inviteCode",
            "baseName": "invite_code",
            "type": "string"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GroupInviteMessagePayload.attributeTypeMap;
    }
}

