/**
 * WhatsAPI Go
 * The V2 of WhatsAPI Go
 *
 * The version of the OpenAPI document: 2.0
 * Contact: manjit@sponsorbook.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ReplyButton {
    'buttonId'?: string;
    'buttonText'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "buttonId",
            "baseName": "button_id",
            "type": "string"
        },
        {
            "name": "buttonText",
            "baseName": "button_text",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ReplyButton.attributeTypeMap;
    }
}

